### ISSUE TITLE
refactor(stormy): auto reaction with repostReactions

### ISSUE THREAD

**Issue by perzeuss** [mavolin/stormy#11]
Stormy reacts to new messages with repostReactions and then with autoReactions. 

Issue here:
- Stormy should react with autoReactions first
- After that, Stormy should only react with repostReactions when it's configured:
````yml
    repostReactions: # array of repost reactions
      - target: 456 # the channel that shall be posted to
        reaction: 🍇 # the reaction that triggers a repost
        autoReact: true # whether the reaction should be added at new messages, default: false
```
